Inisialisasi RESTful API dengan echo
9tw/ALTA-store pull request #5
Opened 2021-02-21 02:15 UTC by 9tw

#4 Tolong di review dulu sebelum di merge ke develop

2021-02-21 03:22 UTC, ridhof requested changes
sama bisa minta tolong file go mod sama go sum (kalau ada) di-commit juga mas?
karena itu perlu juga buat menjalankan projectnya

2021-02-21 03:22 UTC, ridhof commented on echo.go
> +
mungkin di baris terakhir ini bisa ditambahkan kayak yang di tugas gini mas
![function main](https://cdn.discordapp.com/attachments/750304684836651039/812886348934414346/VqlW8svgfcIb2fdCbqvZJQAISkIAEJCABCQC1tVVMnZzKypUre8zDI4Lrxo0bcUvftFjndaBJCABCUhAAhKQgASf4G0tDR85vf9N.png)
soalnya sewaktu saya coba jalankan pakai `go run echo.go` itu ternyata ga bisa diakses di http://localhost:8000/

2021-02-21 04:43 UTC, 9tw commented on echo.go
> +
Oke mas sudah saya tambah kan

2021-02-21 07:54 UTC, ridhof approved these changes

2021-02-21 07:58 UTC, ridhof requested changes
tambahkan 1 endpoint sebagai sample yang menunjukkan bahwa sistem sedang running

contohnya: [https://covid19hub-api.now.sh/api](https://covid19hub-api.now.sh/api)

2021-02-21 07:58 UTC, ridhof commented on echo.go
> +
tambahkan controller sample untuk menunjukkan bahwa sistem berhasil running

contohnya seperti ini [https://covid19hub-api.now.sh/api](https://covid19hub-api.now.sh/api)

2021-02-22 03:48 UTC, ridhof approved these changes
kalau sudah ditambahkan, bisa langsung di merge ke develop mas

2021-02-22 03:48 UTC, ridhof commented on echo.go
> +func Hello(c echo.Context) error {
sebetulnya opsional tapi apa bisa ditambahkan komentar di sebelum function Hello ya mas?
kalau tanpa komentar, ada warning seperti gambar di bawah:

![warning function Hello](https://cdn.discordapp.com/attachments/750304684836651039/813252273354178590/unknown.png)

komentarnya biasanya formatnya nama function terus keterangan nya, contohnya seperti di bawah

![komentar sebelum function](https://cdn.discordapp.com/attachments/750304684836651039/813252674321383464/unknown.png)


```suggestion
// Hello menginformasikan bahwa API berjalan dengan baik
func Hello(c echo.Context) error {
```

2021-02-22 03:48 UTC, ridhof commented on echo.go
> +  e.Get("/hello", Hello)
ini ada typo di saya mas Edo, waktu dijalanin jadi error karena function Get() tidak dikenali, seperti gambar di bawah

![Error method Get tidak dikenali](https://cdn.discordapp.com/attachments/750304684836651039/813252007225196574/unknown.png)

bisa minta tolong diganti jadi GET kapital semua mas? kalau GET nya kapital waktu saya tes di browser sudah bisa jalan dengan sesuai

![berjalan dengan baik](https://cdn.discordapp.com/attachments/750304684836651039/813251490650914876/unknown.png)

```suggestion
  e.GET("/hello", Hello)
```

2021-02-24 16:04 UTC, merged